Repository sourcelevel/linters, pull requests merged in 2020-07, with the labels that each got.

#6 Update Rubocop rules to be compatible with 0.83
  .rubocop.yml
Labels: engine-update

#5 Update Rubocop config file to follow 0.82
  .rubocop.yml
Labels: engine-update

#7 Remove TODO mention in .credo.exs
  .credo.exs
Labels: bug

#8 Remove TODO mention in .credo.exs in `latest` channel
  .credo.exs
Labels: bug

#10 Add tmp to Rubocop to exclude dirs list
  .rubocop.yml
Labels: enhancement

#9 Add tmp to Rubocop to exclude dirs list
  .rubocop.yml
Labels: enhancement
